spring:
  cloud:
      consul:
           host: localhost
           port: 8500
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usermodule?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Balaji@407
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
             hibernate:
                     dialect: org.hibernate.dialect.MySQL8Dialect  

server:
       port : 8081

message:
       greeting: default